### PR TITLE
Adapted to Selenium 4.11.2

### PR DESCRIPTION
**Pull request by DGrothe-PhD**
Looks as if your code works with selenium prior to 4.10.x or similar, so when I freshly installed selenium today, version 4.11.2, a couple of lines turned out to be deprecated. Hope this helps 🖐

### CODE REVIEW

**Comment by ReinhardLenz** [comment]
wow, Ich flippe aus, somebody has read this github file! Thanks a lot for commenting and improving. I have been trying to get latest Chromebook webdriver working on my Chromebook on Linux, but I am completely lost with it.   There is this guy https://www.youtube.com/watch?v=OlMX0gxyL58
[https://www.bing.com/th?id=OVP.IPTu5rDHdIcIxRM9Ac1y8QHgFo&pid=Api]<https://www.youtube.com/watch?v=OlMX0gxyL58>
New Dedicated Chrome Browser for Automated Testing || Major Impact on Selenium || Chrome 115.x<https://www.youtube.com/watch?v=OlMX0gxyL58>
In this video, I have explained New Dedicated Chrome Browser for Automated Testing || Major Change in Selenium Schedule a meeting in case of any queries/guidance/counselling: https://calendly.com/naveenautomationlabs ~~~Subscribe to this channel, and press bell icon to get some interesting videos on Selenium and Automation: https://www.youtube ...
www.youtube.com
but I cannot replicate it, because I used Python.

________________________________
Lähettäjä: Daniela Grothe ***@***.***>
Lähetetty: maanantai 14. elokuuta 2023 20.59
Vastaanottaja: ReinhardLenz/Stuttgart_Boerse_selenium_Python ***@***.***>
Kopio: Subscribed ***@***.***>
Aihe: [ReinhardLenz/Stuttgart_Boerse_selenium_Python] Adapted to Selenium 4.11.2 (PR #1)


Looks as if your code works with selenium prior to 4.10.x or similar, so when I freshly installed selenium today, version 4.11.2, a couple of lines turned out to be deprecated. Hope this helps 🖐

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1

Commit Summary

  *   36994ff<https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1/commits/36994ff3146b50616391370e1658846e09b03c99> adapt to selenium 4.11.2, ref.: selenium removed 16 deprecated...
  *   2321d5f<https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1/commits/2321d5f00b91d461916e56c32fc94b31353b0220> Include requirements

File Changes

(2 files<https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1/files>)

  *   M Anleihen_F_suchen_euro_list_get_beautiful.py<https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1/files#diff-439d15e6d245e2bb2c3911a8ee4db274ecb56825bac8c513b1bef5943d41f7ce> (26)
  *   M README.md<https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5> (8)

Patch Links:

  *   https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1.patch
  *   https://github.com/ReinhardLenz/Stuttgart_Boerse_selenium_Python/pull/1.diff

**Comment by DGrothe-PhD** [comment]
As I understood the guy's video, as long as Google Chrome is automatically updated, chrome driver must either be regularly replaced with a newer version corresponding to Google Chrome version; or the environment should be a separate test environment with Google Chrome not being automatically updated. (To me, this sounds a bit far from what an end user might like to do every week after all just for getting the trading information...)

**Comment by ReinhardLenz** [comment]
TausenDank!  Updated Selenium 4.11.2 It works! Both on Windows and linux.

**Comment by DGrothe-PhD** [comment]
Okay, but I wonder if you might have closed the PR by mistake instead of merging!?

**Pull request merged**
